### ISSUE TITLE
RB problem

### ISSUE THREAD

**Issue by biankawolo** [qiboteam/qibocal#1011]
Dear Qibo!
Fot standard RB for one qubit "if a dictionary is given  (in actions.yml) the list will be built" - not true :) There seems to be a problem with yml file. I put in my actions:
```
depths:
     start: 1
     stop: 50
      step: 25
```
and it does not generate any report. 
Thanks for help!
