### ISSUE TITLE
Ramsey fitting not working

### ISSUE THREAD

**Issue by maxhant** [qiboteam/qibocal#225]
The fits are giving me a 7MHz shift while I am getting 8 oscillations as expected, so it should be close to 0Hz. I am not sure if this is because of @AlejandroSopena changes, but I don't think that I've had this problem before. 

Running on main for qibolab and qibocal, and the action is the following:
```yml
  ramsey_frequency_detuned:
    delay_between_pulses_start: 4
    delay_between_pulses_end: [1000] #t_end (optimal) = 3.5 * T2
    delay_between_pulses_step: 8
    n_osc: 8
    software_averages: 1
    points: 1
```

**Results**:

![image](https://user-images.githubusercontent.com/52139175/215529084-7bec40f3-725c-4d28-8e6a-c2008b660449.png)
