### ISSUE TITLE
Flipping fitting not showing correct amplitude

### ISSUE THREAD

**Issue by maxhant** [qiboteam/qibocal#227]
Using the following action:
```
  flipping:
    nflips_max: 30
    nflips_step: 2
    software_averages: 1
    points: 1
```
and both mains, for the qili1q_os2 runcard, I get a corrected amplitude of 0:

**result**:
![image](https://user-images.githubusercontent.com/52139175/215567063-5a417762-fab3-49d9-bc5a-7d8e02649396.png)
