### ISSUE TITLE
Global qubits parameter in runcard to action specific parameter

### ISSUE THREAD

**Issue by wilkensJ** [qiboteam/qibocal#301]
Would it be possible to specify the `qubits` parameter in the qibocal runcards in each action instead of globally? When using `niGSC` protocols, it could be very useful to specify target qubits in the same runcard.
But I can see that, when characterizing only one qubit with many actions, the global parameter is very useful.
So instead of
https://github.com/qiboteam/qibocal/blob/9a27c90074150cec3106010a16b2c104011ca451/runcards/niGSC.yml#L1-L28

Have something like

```yaml
backend: numpy
format: pickle

actions:
  standardrb:
    qubits: [0]
    nqubits: 5
    depths: [1,3,5,7,10]
    runs: 2
    nshots: 1024
    noise_model: PauliErrorOnUnitary
    noise_params: [0.01, 0.01, 0.01]
  XIdrb:
    qubits: [2]
    nqubits: 5
    depths: [1,2,3,4,5,6,7,8,9,10]
    runs: 5
    nshots: 10
    noise_model: PauliErrorOnX
    noise_params: [0.05, 0.01, 0.01]
  simulfilteredrb:
    qubits: [0,1,2,3,4]
    nqubits: 5
    depths: [1,3,5,7,10]
    runs: 2
    nshots: 1024
    noise_model: PauliErrorOnUnitary
    noise_params: [0.01, 0.01, 0.01]
```
