### ISSUE TITLE
Allow sequential execution with `qubits`

### ISSUE THREAD

**Issue by vodovozovaliza** [qiboteam/qibocal#394]
I think `qubits` parameter in the runcard should be specified as a 2d list to differentiate sequential and simultaneous execution of the protocols. For example, one could write:

```yml
- id:  rb
  priority: 0
  operation: standard_rb
  qubits: [[0], [1], [0,1]]
  parameters:
    nqubits: 5
    depths: [1,3,5,10,15,20]
    niter: 10
    nshots: 1000
```
instead of
```yml
- id:  rb 1
  priority: 0
  next: rb 2
  operation: standard_rb
  qubits: [0]
  ...

- id: rb 2
  priority: 0
  next: rb 3
  operation: standard_rb
  qubits: [1]
  ...

- id: rb 3
  priority: 0
  operation: standard_rb
  qubits: [0,1]
  ...
```
