### ISSUE TITLE
Errors in the generation of the new_platform.yml runcard

### ISSUE THREAD

**Issue by aorgazf** [qiboteam/qibocal#459]
Hi,
After successfully executing a resonator flux spectroscopy using the follwing action script:
```
platform: qw5q_gold_qblox
qubits: [0, 1, 2, 3, 4]
format: csv
actions:
  - id: resonator flux dependence
    priority: 0
    operation: resonator_flux
    parameters:
      freq_width: 8_000_000
      freq_step: 50_000
      bias_width: 2
      bias_step:  0.01
      nshots: 1000
      relaxation_time: 2000
```
I tried using the new platform runcard `new_platform.yml`, but there seems to be a problem with its generation (related to dump?) where the `topology` key is nested inside of `native_gates`

```
nqubits: 5
qubits: [0, 1, 2, 3, 4]
settings: {nshots: 1024, sampling_rate: 1000000000, relaxation_time: 20000}
native_gates:
    topology:
    - [0, 2]
    - [1, 2]
    - [2, 3]
    - [2, 4]
    single_qubit:
        0:
            RX: {duration: 40, amplitude: 0.5037576688262035, shape: 'Drag(5, 0.200)',
                qubit: 0, frequency: 5050222356, relative_start: 0, start: 0, phase: 0,
                type: qd}
            MZ: {duration: 2000, amplitude: 0.1, shape: Rectangular(), qubit: 0, frequency: 7212247247,
                relative_start: 0, start: 0, phase: 0, type: ro}
        1:
            RX: {duration: 40, amplitude: 0.5091870515531648, shape: 'Drag(5, 0.000)',
                qubit: 1, frequency: 4851448063, relative_start: 0, start: 0, phase: 0.0,
                type: qd}
            MZ: {duration: 2000, amplitude: 0.2, shape: Rectangular(), qubit: 1, frequency: 7453057759,
                relative_start: 0, start: 0, phase: 0.0, type: ro}
        2:
            RX: {duration: 40, amplitude: 0.4961740399301971, shape: 'Drag(5, -0.100)',
                qubit: 2, frequency: 5796025841, relative_start: 0, start: 0, phase: 0.0,
                type: qd}
            MZ: {duration: 2000, amplitude: 0.25, shape: Rectangular(), qubit: 2,
                frequency: 7655018835, relative_start: 0, start: 0, phase: 0.0, type: ro}
        3:
            RX: {duration: 40, amplitude: 0.4977305637146838, shape: 'Drag(5, 0.300)',
                qubit: 3, frequency: 6759863862, relative_start: 0, start: 0, phase: 0.0,
                type: qd}
            MZ: {duration: 2000, amplitude: 0.2, shape: Rectangular(), qubit: 3, frequency: 7803478785,
                relative_start: 0, start: 0, phase: 0.0, type: ro}
        4:
            RX: {duration: 40, amplitude: 0.56468497579218, shape: 'Drag(5, -0.100)',
                qubit: 4, frequency: 6590262523, relative_start: 0, start: 0, phase: 0.0,
                type: qd}
            MZ: {duration: 2000, amplitude: 0.4, shape: Rectangular(), qubit: 4, frequency: 8058893357,
                relative_start: 0, start: 0, phase: 0.0, type: ro}
    two_qubit:
        0-2:
            CZ:
            - {duration: 40, amplitude: 0.142, shape: 'Exponential(12, 5000, 0.1)',
                qubit: 2, frequency: 0, relative_start: 0, start: 0, phase: 0.0, type: qf}
        1-2:
            CZ:
            - {duration: 32, amplitude: 0.175, shape: 'Exponential(2, 2700, 0.1)',
                qubit: 2, frequency: 0, relative_start: 0, start: 0, phase: 0.0, type: qf}
        2-3:
            CZ:
            - {duration: 32, amplitude: 0.6025, shape: 'Exponential(12, 5000, 0.1)',
                qubit: 3, frequency: 0, relative_start: 0, start: 0, phase: 0.0, type: qf}
        2-4:
            CZ:
            - {duration: 40, amplitude: -0.1355, shape: 'Exponential(10, 3000, 0.05)',
                qubit: 4, frequency: 0, relative_start: 0, start: 0, phase: 0.0, type: qf}
characterization:
    single_qubit:
        0:
            bare_resonator_frequency: 7200000000
            readout_frequency: 7212247247
            drive_frequency: 5050222356
            anharmonicity: 291463266
            Ec: 270000000
            Ej: 11400000000
            g: 107000000
            assigment_fidelity: 0.0
            sweetspot: 0.5581847237365478
            peak_voltage: 0
            pi_pulse_amplitude: 0.5037576688262035
            T1: 5857
            T2: 0
            T2_spin_echo: 0
            state0_voltage: 0
            state1_voltage: 0
            mean_gnd_states: [0.00015380554580212232, -0.005805669098239971]
            mean_exc_states: [0.0035276752607135103, -0.004859829382768821]
            resonator_polycoef_flux: []
            threshold: 0.0005184204099139629
            iq_angle: -0.2733264522060816
            mixer_drive_g: 0.0
            mixer_drive_phi: 0.0
            mixer_readout_g: 0.0
            mixer_readout_phi: 0.0
            classifiers_hpars: {}
        1:
            bare_resonator_frequency: 7400000000
            readout_frequency: 7453057759
            drive_frequency: 4851448063
            anharmonicity: 292584018
            Ec: 270000000
            Ej: 11400000000
            g: 11400000
            assigment_fidelity: 0.0
            sweetspot: 0.25159645420785115
            peak_voltage: 0
            pi_pulse_amplitude: 0.5091870515531648
            T1: 1253
            T2: 0
            T2_spin_echo: 0
            state0_voltage: 0
            state1_voltage: 0
            mean_gnd_states: [-0.002511367520388916, 0.004153506157808853]
            mean_exc_states: [-0.004924608081609944, 0.0003488906423865549]
            resonator_polycoef_flux: []
            threshold: -0.0006226385364404459
            iq_angle: 2.1360502757587594
            mixer_drive_g: 0.0
            mixer_drive_phi: 0.0
            mixer_readout_g: 0.0
            mixer_readout_phi: 0.0
            classifiers_hpars: {}
        2:
            bare_resonator_frequency: 7600000000
            readout_frequency: 7655018835
            drive_frequency: 5796025841
            anharmonicity: 276187576
            Ec: 270000000
            Ej: 16000000000
            g: 83600000
            assigment_fidelity: 0.0
            sweetspot: -0.336861343848651
            peak_voltage: 0
            pi_pulse_amplitude: 0.4961740399301971
            T1: 4563
            T2: 0
            T2_spin_echo: 0
            state0_voltage: 0
            state1_voltage: 0
            mean_gnd_states: [-0.0032186027443616675, -0.00037197685976768174]
            mean_exc_states: [-0.001892849842927319, -0.0027580154138169676]
            resonator_polycoef_flux: []
            threshold: 0.00011290265850759157
            iq_angle: 1.0636414819271858
            mixer_drive_g: 0.0
            mixer_drive_phi: 0.0
            mixer_readout_g: 0.0
            mixer_readout_phi: 0.0
            classifiers_hpars: {}
        3:
            bare_resonator_frequency: 7800000000
            readout_frequency: 7803478785
            drive_frequency: 6759863862
            anharmonicity: 262310994
            Ec: 270000000
            Ej: 21200000000
            g: 54300000
            assigment_fidelity: 0.0
            sweetspot: -1.0514505842275377
            peak_voltage: 0
            pi_pulse_amplitude: 0.4977305637146838
            T1: 4232
            T2: 0
            T2_spin_echo: 0
            state0_voltage: 0
            state1_voltage: 0
            mean_gnd_states: [-0.0010512624017023557, -0.00712503217572803]
            mean_exc_states: [0.002121668036387939, -0.003562232098633502]
            resonator_polycoef_flux: []
            threshold: -0.004242115141640443
            iq_angle: -0.8432144807352956
            mixer_drive_g: 0.0
            mixer_drive_phi: 0.0
            mixer_readout_g: 0.0
            mixer_readout_phi: 0.0
            classifiers_hpars: {}
        4:
            bare_resonator_frequency: 8000000000
            readout_frequency: 8058893357
            drive_frequency: 6590262523
            anharmonicity: 261390626
            Ec: 270000000
            Ej: 21200000000
            g: 62700000
            assigment_fidelity: 0.0
            sweetspot: 0.6090658646544942
            peak_voltage: 0
            pi_pulse_amplitude: 0.56468497579218
            T1: 492
            T2: 0
            T2_spin_echo: 0
            state0_voltage: 0
            state1_voltage: 0
            mean_gnd_states: [0.0017155003574845303, 0.0004829473412141074]
            mean_exc_states: [-5.9049086909026765e-05, 0.0029005369264981273]
            resonator_polycoef_flux: []
            threshold: 0.0006647302110707933
            iq_angle: -2.203988949908468
            mixer_drive_g: 0.0
            mixer_drive_phi: 0.0
            mixer_readout_g: 0.0
            mixer_readout_phi: 0.0
            classifiers_hpars: {}
```
