### ISSUE TITLE
Flipping fitting function fails

### ISSUE THREAD

**Issue by aorgazf** [qiboteam/qibocal#502]
Hi!
The fitting function of the `flipping` routine does not seem to work.
![image](https://github.com/qiboteam/qibocal/assets/55031026/f3b4c223-48ec-400c-8cef-2bc1e9201bad)

Below is the action parameters used with `qw5q_gold_qblox`
```yml
  - id: flipping
    priority: 0 #70
    operation: flipping
    # next: t1
    parameters:
      nflips_max: 30
      nflips_step: 1
```
