### ISSUE TITLE
Wrong platform used when not specified in the runcard

### ISSUE THREAD

**Issue by GabrielePalazzo** [qiboteam/qibocal#727]
If there is no platform specified in the runcard, `qq` pick the wrong platform when if `--platform` is specified.

Command used:
```
qq auto actions.yml --platform iqm5q
```
Example runcard:
``` yaml
actions:

  - id: resonator_spectroscopy high power
    priority: 0
    operation: resonator_spectroscopy
    main: resonator_spectroscopy low power
    parameters:
      freq_width: 60_000_000
      freq_step: 500_000
      amplitude: 0.5
      power_level: high
      nshots: 1024
      relaxation_time: 50000

  - id: resonator_spectroscopy low power
    priority: 0
    operation: resonator_spectroscopy
    # main: qubit spectroscopy
    # main: resonator punchout
    parameters:
      freq_width: 60_000_000
      freq_step: 500_000
      amplitude: 0.015
      power_level: low
      nshots: 1024
      relaxation_time: 50000
```

Output:
``` bash
[Qibo 0.2.4|INFO|2024-02-23 14:21:26]: Loading platform dummy
[Qibo 0.2.4|INFO|2024-02-23 14:21:26]: Using qibolab (dummy) backend on /CPU:0
[Qibocal 0.0.7|INFO|2024-02-23 14:21:26]: Creating directory 2024-02-23-000-gabrielepalazzo.
[Qibo 0.2.4|INFO|2024-02-23 14:21:26]: Connecting to instrument <qibolab.instruments.dummy.DummyInstrument object at 0x7fd2a6f3c550>.
[Qibo 0.2.4|INFO|2024-02-23 14:21:26]: Connecting to dummy instrument.
[Qibo 0.2.4|INFO|2024-02-23 14:21:26]: Connecting to instrument <qibolab.instruments.dummy.DummyLocalOscillator object at 0x7fd2a6f3c400>.
[Qibocal 0.0.7|INFO|2024-02-23 14:21:26]: Executing mode autocalibration on resonator_spectroscopy high power iteration 0.
[Qibo 0.2.4|INFO|2024-02-23 14:21:26]: Minimal execution time (sweep): 6.389760000000001
[Qibocal 0.0.7|INFO|2024-02-23 14:21:26]: Finished acquisition in less than 1 second.
[Qibocal 0.0.7|INFO|2024-02-23 14:21:26]: Finished fit in less than 1 second.
[Qibocal 0.0.7|INFO|2024-02-23 14:21:26]: Executing mode autocalibration on resonator_spectroscopy low power iteration 0.
[Qibo 0.2.4|INFO|2024-02-23 14:21:26]: Minimal execution time (sweep): 6.389760000000001
[Qibocal 0.0.7|INFO|2024-02-23 14:21:26]: Finished acquisition in less than 1 second.
[Qibocal 0.0.7|WARNING|2024-02-23 14:21:26]: lorentzian_fit: the fitting was not successful
[Qibocal 0.0.7|INFO|2024-02-23 14:21:26]: Finished fit in less than 1 second.
[Qibo 0.2.4|INFO|2024-02-23 14:21:27]: Disconnecting dummy instrument.
```
`echo $QIBOLAB_PLATFORMS` gives
```
/home/gabrielepalazzo/qibolab_platforms_qrc
```
I'm using:
 - qibolab: main
 - qibocal: main
 - qibolab_platforms_qrc: main
