### ISSUE TITLE
Routines do not run on the specified qubits

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibocal#732]
If I try `qq acquire` and `qq report` on the following action runcard
```yaml
platform: dummy

qubits: [0]

actions:

  - id: resonator flux dependence
    priority: 0
    operation: resonator_flux
    parameters:
      freq_width: 10_000_000
      freq_step: 200_000
      bias_width: 0.6
      bias_step:  0.02
      nshots: 1024
      relaxation_time: 5000
```
I get a report that contains all five qubits of the dummy platform, while I would expect to get only qubit-0.
