### ISSUE TITLE
Missing extension to the results filename for singleshot classification

### ISSUE THREAD

**Issue by GabrielePalazzo** [qiboteam/qibocal#746]
The results file obtained by the singleshot classification routine is named `results` instead of `results.json`.

Runcard used:

``` yaml
actions:

  - id: t1
    priority: 0
    operation: t1
    main: single_shot_classification
    parameters:
      delay_before_readout_start: 16
      delay_before_readout_end: 2000
      delay_before_readout_step: 20

  - id: single_shot_classification
    priority: 0
    operation: single_shot_classification
    parameters:
      nshots: 1024
```
